environment: ember-loose

# FIXME: Remove include key before merge
include:
  - 'app/models/**'
  - 'app/routes/**'
  - 'app/components/rentals/filter.*'
  - 'app/components/map.*'
  - 'app/components/share-button.*'
